# Generated by Django 3.1.1 on 2020-09-14 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_auto_20200914_2217"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="last_login",
            field=models.DateField(null=True),
        ),
    ]
